<?php
$this->headTitle()->append(_t('反馈'));
$this->placeholder('main')->captureStart();
?>
<h1><?php _e('反馈') ?></h1>
<p><?php _e('你可以在这里提交 Bug, 新功能需求以及留言。') ?></p>
<div id="disqus_thread"></div>
<script type="text/javascript">
var disqus_developer = 1;
(function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://mypdc.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<a class="size10 gray" href="http://disqus.com">Powered by <span class="logo-disqus">Disqus</span></a>

<?php
$this->placeholder('main')->captureEnd();
$this->placeholder('sidebar')->captureStart();
?>
<h3><?php _e('什么是PDC？') ?></h3>
<p>
    <ul class="size12">
        <li><strong>P</strong>ersonal <strong>D</strong>ata <strong>C</strong>enter</li>
        <li><strong>P</strong>rivate <strong>D</strong>ata <strong>C</strong>enter</li>
        <li><strong>P</strong>ermanent <strong>D</strong>ata <strong>C</strong>enter</li>
        <li><strong>P</strong>rogrammer's <strong>D</strong>ata <strong>C</strong>enter</li>
    </ul>
</p>
<p><?php _e('简单说，这里就是你的个人数据中心，而且是私有的、永久的。') ?></p>
<h3><?php _e('我能在这里做什么？') ?></h3>
<p><?php _e('你可以将平时遇到的经典代码收集于此以供未来的项目中重用；你可以将一篇优美的博文、一些好听的歌曲收藏于此。') ?></p>
<p><?php echo sprintf(_t('更多疑问请参见 %s这里%s'), '<a href="/about">', '</a>') ?></p>
<?php $this->placeholder('sidebar')->captureEnd()?>
