<?php
$this->headTitle()->append(_t('重置密码'));
$obj = $this;
$checkError = function($field) use ($obj) {
    if (isset($obj->message[$field]))
        echo '<span class="error">', $obj->message[$field], '</span>';
};
$this->placeholder('main')->captureStart();
?>
<h1><?php _e('重置密码') ?></h1>
<?php if($this->sent):?>
<div class="notice success"><?php _e('一封包含重置密码链接的邮件已发送至你刚才提交的邮箱，请查收。') ?></div>
<?php elseif (isset($this->newpass)):?>
<div class="notice success"><?php echo sprintf(_t('你的密码已被重置为 %s，请重新登录。'), $this->newpass) ?></div>
<?php else:?>
<form action="/reset_password" method="post">
<table class="vert">
    <tr class="odd">
        <th width="100"><?php _e('你的用户名')?></th>
        <td><input type="text" class="text" name="username" value="<?php echo $this->username?>" /> <?php $checkError('username') ?></td>
    </tr>
    <tr class="even">
        <th><?php _e('你的电子邮件')?></th>
        <td><input type="text" class="text" name="email" value="<?php echo $this->email?>" /> <?php $checkError('email') ?></td>
    </tr>
    <tr class="odd">
        <th><?php _e('验证码')?></th>
        <td>
            <?php
                $zci = Zend_Registry::get('Zend_Captcha_Image');
                echo $zci->render();
            ?>
            <input type="hidden" name="captchaId" value="<?php echo $this->captchaId?>" />
            <input type="text" autoComplete="off" class="text" name="captcha" value="" /> <?php $checkError('captcha') ?>
        </td>
    </tr>
    <tr class="odd">
        <th></th>
        <td><button name="action_button" class="classy" type="submit"><span><?php _e('提交') ?></span></button></td>
    </tr>
</table>
<?php if($this->next):?>
<input type="hidden" value="<?php echo $this->next?>" name="next" />
<?php endif;?>
</form>
<?php
endif;
$this->placeholder('main')->captureEnd();
$this->placeholder('sidebar')->captureStart();
?>
<h3><?php _e('重置密码') ?></h3>
<p><?php _e('输入你注册时填写的电子邮件地址，提交后系统会发送重置密码的链接到这个邮箱。') ?></p>
<?php $this->placeholder('sidebar')->captureEnd()?>
