<!DOCTYPE html> 
<html>
<head>
<?php
$this->headScript()->prependFile('/static/js/jquery-1.4.2.min.js');
if (APPLICATION_ENV === 'development')
    $this->headScript()->appendFile('/static/js/pdc.orig.js');
else
    $this->headScript()->appendFile('/static/js/pdc.js?v201010281306');
$this->headLink()->prependStylesheet('/static/css/style.css');
//$this->headMeta()->appendName('google-site-verification', 'cQen40avov7OCdJPqY2Wkk3lDfk2wreYfqeEbQ-ksbg');
$this->headMeta()->appendName('description', 'MyPDC 是你的个人数据中心，而且是私有的、永久的。MyPDC is your personal data center, and private, permanent.');
echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->headScript();
echo $this->headStyle();
?>
</head>
<body>
    <div id="header">
        <div class="container">
            <div id="logo">
                <a href="/"><img src="/static/image/logo.png" alt="MyPDC" title="MyPDC" /></a>
            </div>
            <div id="nav">
                <ul>
                    <?php if ($this->user):?>
                    <li class="avatarname"><a href="/"><img width="20" height="20" alt="<?php echo $this->user->username ?>" src="<?php $this->avatar($this->user) ?>"><?php _h($this->user->username) ?></a></li>
                    <li><a href="/code"><?php _e('代码') ?></a></li>
                    <li><a href="/note"><?php _e('记事本') ?></a></li>
                    <!--li><a href="/collection"><?php _e('收藏') ?></a></li-->
                    <li><a href="/setting"><?php _e('设置') ?></a></li>
                    <?php if ($this->user->role == 'admin') echo '<li><a href="/admin">', _t('管理'), '</a></li>'; ?>
                    <li><a href="/signout"><?php _e('登出') ?></a></li>
                    <?php else:?>
                    <li><a href="/signin"><?php _e('登录') ?></a></li>
                    <li><a href="/signup"><?php _e('注册') ?></a></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
    <hr class="clear sep10" />
    <div id="content" class="container">
<?php echo $this->placeholder('main')?>
<?php echo $this->placeholder('sidebar')?>
    </div>
    <hr class="clear sep10" />
    <div id="footer">
        <div class="container">
            <div id="poweredby"><a target="_blank" href="http://zendframework.com/"><img border="0" align="absmiddle" alt="Powered by Zend Framework" title="Powered by Zend Framework" src="/static/image/zf.gif"></a> &nbsp; <a target="_blank" href="http://www.postgresql.org/"><img border="0" align="absmiddle" alt="Powered by Postgres SQL" title="Powered by Postgres SQL" src="/static/image/pg.png"></a> &nbsp; <a target="_blank" href="http://code.google.com/p/redis/"><img border="0" align="absmiddle" alt="Powered by Redis" title="Powered by Redis" src="/static/image/redis.png"></a></div>
            <div>&copy;2010 <a href="<?php echo APPURL ?>"><?php echo APPNAME_HTML?></a> by <a href="http://about.me/ichuan">ichuan</a>. <a href="/about"><strong>About</strong></a> | <a href="/feedback"><strong>Feedback</strong></a> | <a href="/plan"><strong>Plan</strong></a> | <a href="#top"><strong>Top&uarr;</strong></a> <span id="language"><a onclick="return resetLang('en')" href="#en">English</a> <a href="#zh" onclick="return resetLang('zh')">简体中文</a></span> </div>
        </div>
    </div>
</body>
<?php if (APPLICATION_ENV === 'development') echo $this->layout()->content?>
</html>
